{{- if not .Values.global.ci }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okp
  template:
    metadata:
      labels:
        app: okp
    spec:
      containers:
      - name: okp
        image: registry.redhat.io/offline-knowledge-portal/rhokp-rhel9:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - |
            /opt/solr/bin/solr start --user-managed --force -m 1g
            rm -f /etc/httpd/conf.d/ssl.conf
            exec httpd -D FOREGROUND
        env:
        - name: SOLR_HOST_BIND
          value: "0.0.0.0"
        - name: MIMIR_HTTPD_SERVER_NAME
          value: "localhost"
        - name: COMPRESSED
          value: "true"
        - name: ENCRYPT
          value: "false"
        ports:
        - containerPort: 8080
          name: httpd
          protocol: TCP
        - containerPort: 8983
          name: solr
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: okp-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: httpd
  - port: 8983
    targetPort: 8983
    name: solr
  selector:
    app: okp
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: okp
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: okp-svc
  port:
    targetPort: httpd
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
{{- end }}
